# Generated by Django 5.2.6 on 2026-06-01 18:14

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_transaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creditor_name', models.CharField(max_length=200, verbose_name='Кредитор / должник')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Сумма')),
                ('type', models.CharField(choices=[('owed_to_me', 'Мне должны'), ('i_owe', 'Я должен')], max_length=10, verbose_name='Тип')),
                ('due_date', models.DateField(verbose_name='Дата возврата')),
                ('status', models.CharField(choices=[('active', 'Активен'), ('paid', 'Погашен'), ('overdue', 'Просрочен')], default='active', max_length=10, verbose_name='Статус')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Долг',
                'verbose_name_plural': 'Долги',
                'ordering': ['status', 'due_date'],
            },
        ),
        migrations.CreateModel(
            name='RecurringPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Сумма')),
                ('type', models.CharField(choices=[('income', 'Доход'), ('expense', 'Расход')], max_length=7, verbose_name='Тип')),
                ('frequency', models.CharField(choices=[('weekly', 'Еженедельно'), ('monthly', 'Ежемесячно'), ('quarterly', 'Ежеквартально'), ('yearly', 'Ежегодно')], default='monthly', max_length=10, verbose_name='Периодичность')),
                ('next_date', models.DateField(verbose_name='Следующий платёж')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_payments', to='finance.account', verbose_name='Счёт')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_payments', to='finance.category', verbose_name='Категория')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Регулярный платёж',
                'verbose_name_plural': 'Регулярные платежи',
                'ordering': ['next_date'],
            },
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('message', models.TextField(blank=True, verbose_name='Сообщение')),
                ('remind_date', models.DateField(verbose_name='Дата напоминания')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Выполнено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reminders', to='finance.transaction', verbose_name='Связанная транзакция')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Напоминание',
                'verbose_name_plural': 'Напоминания',
                'ordering': ['is_completed', 'remind_date'],
            },
        ),
    ]
