# Generated by Django 5.2.6 on 2026-06-01 21:17

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_debt_recurringpayment_reminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_favorite',
            field=models.BooleanField(default=False, verbose_name='Избранный'),
        ),
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Баланс'),
        ),
    ]
